local M = {}

local defaults = {
  bold_functions = true,
  italic_comments = true,
  italic_keywords = true,
  terminal_colors = true,
  transparent = false,
}

M.config = vim.deepcopy(defaults)

function M.setup(opts)
  M.config = vim.tbl_deep_extend("force", defaults, opts or {})
end

local function set_terminal_colors(p)
  for index, color in ipairs(p.term) do
    vim.g["terminal_color_" .. (index - 1)] = color
  end
end

local function apply(highlights)
  for group, spec in pairs(highlights) do
    vim.api.nvim_set_hl(0, group, spec)
  end
end

function M.load(opts)
  if opts then
    M.setup(opts)
  end

  vim.cmd("highlight clear")
  if vim.fn.exists("syntax_on") == 1 then
    vim.cmd("syntax reset")
  end

  vim.o.background = "dark"
  vim.o.termguicolors = true
  vim.g.colors_name = "anysphere"

  local p = require("anysphere.palette").get()
  local bg = M.config.transparent and "NONE" or p.bg
  local bg_alt = M.config.transparent and "NONE" or p.bg_alt
  local bg_float = M.config.transparent and "NONE" or p.bg_float
  local comment_style = { fg = p.comment, italic = M.config.italic_comments }
  local keyword_style = { fg = p.cyan, italic = M.config.italic_keywords }
  local function_style = { fg = p.peach, bold = M.config.bold_functions }
  local function_semantic_style = { fg = p.gold, bold = false }
  local function_declaration_style = { fg = p.peach, bold = M.config.bold_functions }

  local highlights = {
    Normal = { fg = p.fg, bg = bg },
    NormalNC = { fg = p.fg, bg = bg },
    NormalFloat = { fg = p.fg, bg = bg_float },
    FloatBorder = { fg = p.border, bg = bg_float },
    FloatTitle = { fg = p.fg, bg = bg_float, bold = true },
    Title = { fg = p.fg_activity },
    ColorColumn = { bg = p.bg_range },
    Conceal = { fg = p.fg_muted },
    Cursor = { fg = p.cursor_bg, bg = p.cursor },
    lCursor = { fg = p.cursor_bg, bg = p.cursor },
    CursorIM = { fg = p.cursor_bg, bg = p.cursor },
    CursorColumn = { bg = p.bg_range },
    CursorLine = { bg = p.bg_line },
    CursorLineNr = { fg = p.fg_line_nr_active },
    LineNr = { fg = p.fg_line_nr },
    LineNrAbove = { fg = p.fg_line_nr },
    LineNrBelow = { fg = p.fg_line_nr },
    SignColumn = { fg = p.fg_line_nr, bg = bg },
    FoldColumn = { fg = p.fg_muted, bg = bg },
    Folded = { fg = p.fg_muted, bg = p.bg_fold },
    VertSplit = { fg = p.border, bg = bg },
    WinSeparator = { fg = p.border, bg = bg },
    EndOfBuffer = { fg = p.bg },
    NonText = { fg = p.fg_muted },
    SpecialKey = { fg = p.whitespace },
    Whitespace = { fg = p.whitespace },
    Directory = { fg = p.steel },
    Question = { fg = p.blue },
    QuickFixLine = { fg = p.fg, bg = p.bg_focus },
    MoreMsg = { fg = p.green },
    ModeMsg = { fg = p.fg },
    MsgArea = { fg = p.fg, bg = bg },
    MsgSeparator = { fg = p.border, bg = bg },
    ErrorMsg = { fg = p.red },
    WarningMsg = { fg = p.orange },
    Visual = { bg = p.bg_visual },
    VisualNOS = { bg = p.bg_visual_inactive },
    Search = { fg = p.fg, bg = p.bg_find_highlight },
    IncSearch = { fg = p.fg, bg = p.bg_find },
    CurSearch = { fg = p.fg, bg = p.bg_find },
    Substitute = { fg = p.fg, bg = p.bg_input_option },
    MatchParen = { fg = p.fg, bg = p.bracket_bg },
    Pmenu = { fg = p.fg, bg = p.bg_float },
    PmenuSel = { fg = p.fg, bg = p.bg_visual },
    PmenuKind = { fg = p.purple, bg = p.bg_float },
    PmenuKindSel = { fg = p.fg, bg = p.bg_visual },
    PmenuExtra = { fg = p.fg_muted, bg = p.bg_float },
    PmenuExtraSel = { fg = p.fg, bg = p.bg_visual },
    PmenuSbar = { bg = p.bg_alt },
    PmenuThumb = { bg = p.fg_muted },
    WildMenu = { fg = p.fg, bg = p.bg_menu_selection },
    StatusLine = { fg = p.fg, bg = p.bg_statusline },
    StatusLineNC = { fg = p.fg_muted, bg = p.bg_statusline },
    TabLine = { fg = p.fg, bg = p.bg_statusline },
    TabLineFill = { fg = p.border_dim, bg = p.bg_statusline },
    TabLineSel = { fg = p.fg, bg = p.bg_statusline },
    WinBar = { fg = p.fg, bg = bg },
    WinBarNC = { fg = p.fg_muted, bg = bg },
    SpellBad = { sp = p.red, undercurl = true },
    SpellCap = { sp = p.blue, undercurl = true },
    SpellLocal = { sp = p.cyan, undercurl = true },
    SpellRare = { sp = p.purple, undercurl = true },

    Comment = comment_style,
    Constant = { fg = p.yellow2 },
    String = { fg = p.pink },
    Character = { fg = p.pink },
    Number = { fg = p.gold },
    Boolean = { fg = p.cyan2 },
    Float = { fg = p.gold },
    Identifier = { fg = p.fg },
    Function = function_style,
    Statement = keyword_style,
    Conditional = keyword_style,
    Repeat = keyword_style,
    Label = { fg = p.yellow2 },
    Operator = { fg = p.fg },
    Keyword = keyword_style,
    Exception = keyword_style,
    PreProc = { fg = p.green2 },
    Include = { fg = p.green2 },
    Define = { fg = p.green2 },
    Macro = { fg = p.green2 },
    PreCondit = { fg = p.green2 },
    Type = { fg = p.peach },
    StorageClass = { fg = p.cyan2 },
    Structure = { fg = p.peach },
    Typedef = { fg = p.peach },
    Special = { fg = p.purple },
    SpecialChar = { fg = p.fg },
    Tag = { fg = p.steel },
    Delimiter = { fg = p.fg },
    SpecialComment = comment_style,
    Debug = { fg = p.cyan },
    Underlined = { fg = p.blue, underline = true },
    Ignore = { fg = p.fg_muted },
    Error = { fg = p.red },
    Todo = { fg = p.yellow2, bold = true },

    DiffAdd = { fg = p.git_add, bg = p.bg_diff_add },
    DiffChange = { fg = p.git_change, bg = p.bg_diff_change },
    DiffDelete = { fg = p.git_delete, bg = p.bg_diff_delete },
    DiffText = { fg = p.fg, bg = p.bg_selection_highlight },
    Added = { fg = p.git_add },
    Changed = { fg = p.git_change },
    Removed = { fg = p.git_delete },

    DiagnosticError = { fg = p.red },
    DiagnosticWarn = { fg = p.orange },
    DiagnosticInfo = { fg = p.blue },
    DiagnosticHint = { fg = p.cyan },
    DiagnosticOk = { fg = p.green },
    DiagnosticUnderlineError = { sp = p.red, undercurl = true },
    DiagnosticUnderlineWarn = { sp = p.orange, undercurl = true },
    DiagnosticUnderlineInfo = { sp = p.blue, undercurl = true },
    DiagnosticUnderlineHint = { sp = p.cyan, undercurl = true },
    DiagnosticVirtualTextError = { fg = p.red, bg = bg_alt },
    DiagnosticVirtualTextWarn = { fg = p.orange, bg = bg_alt },
    DiagnosticVirtualTextInfo = { fg = p.blue, bg = bg_alt },
    DiagnosticVirtualTextHint = { fg = p.cyan, bg = bg_alt },
    DiagnosticFloatingError = { fg = p.red, bg = bg_float },
    DiagnosticFloatingWarn = { fg = p.orange, bg = bg_float },
    DiagnosticFloatingInfo = { fg = p.blue, bg = bg_float },
    DiagnosticFloatingHint = { fg = p.cyan, bg = bg_float },
    DiagnosticSignError = { fg = p.red, bg = bg },
    DiagnosticSignWarn = { fg = p.orange, bg = bg },
    DiagnosticSignInfo = { fg = p.blue, bg = bg },
    DiagnosticSignHint = { fg = p.cyan, bg = bg },
    DiagnosticDeprecated = { sp = p.fg_muted, strikethrough = true },
    DiagnosticUnnecessary = { fg = p.bg_comment_range },

    LspReferenceText = { bg = p.bg_word_highlight },
    LspReferenceRead = { bg = p.bg_word_highlight },
    LspReferenceWrite = { bg = p.bg_word_highlight },
    LspInlayHint = { fg = p.fg_inlay, bg = p.bg_inlay },
    LspCodeLens = { fg = p.fg },
    LspCodeLensSeparator = { fg = p.border },

    ["@annotation"] = { fg = p.green2 },
    ["@attribute"] = { fg = p.purple },
    ["@boolean"] = { fg = p.cyan2 },
    ["@character"] = { fg = p.pink },
    ["@character.special"] = { fg = p.fg },
    ["@comment"] = comment_style,
    ["@constant"] = { fg = p.yellow2 },
    ["@constant.builtin"] = { fg = p.cyan2 },
    ["@constant.macro"] = { fg = p.green2 },
    ["@constructor"] = { fg = p.steel },
    ["@diff.delta"] = { fg = p.peach },
    ["@diff.minus"] = { fg = p.fg },
    ["@diff.plus"] = { fg = p.pink },
    ["@function"] = function_style,
    ["@function.builtin"] = { fg = p.cyan2 },
    ["@function.call"] = { fg = p.purple },
    ["@function.macro"] = { fg = p.green2 },
    ["@keyword"] = keyword_style,
    ["@keyword.conditional"] = keyword_style,
    ["@keyword.directive"] = { fg = p.green2 },
    ["@keyword.exception"] = keyword_style,
    ["@keyword.function"] = keyword_style,
    ["@keyword.import"] = { fg = p.purple },
    ["@keyword.operator"] = { fg = p.cyan },
    ["@keyword.repeat"] = keyword_style,
    ["@label"] = { fg = p.yellow2 },
    ["@markup"] = { fg = p.fg },
    ["@markup.heading"] = { fg = p.fg, bold = true },
    ["@markup.heading.1"] = { fg = p.fg, bold = true },
    ["@markup.heading.2"] = { fg = p.fg, bold = true },
    ["@markup.heading.3"] = { fg = p.fg, bold = true },
    ["@markup.heading.4"] = { fg = p.fg, bold = true },
    ["@markup.heading.5"] = { fg = p.fg, bold = true },
    ["@markup.heading.6"] = { fg = p.fg, bold = true },
    ["@markup.italic"] = { fg = p.cyan, italic = true },
    ["@markup.link"] = { fg = p.cyan },
    ["@markup.link.label"] = { fg = p.purple },
    ["@markup.link.url"] = { fg = p.purple, underline = true },
    ["@markup.list"] = { fg = p.fg },
    ["@markup.quote"] = { fg = p.comment },
    ["@markup.raw"] = { fg = p.pink },
    ["@markup.strong"] = { fg = p.yellow2, bold = true },
    ["@module"] = { fg = p.fg_sidebar },
    ["@namespace"] = { fg = p.fg_sidebar },
    ["@number"] = { fg = p.gold },
    ["@number.float"] = { fg = p.gold },
    ["@operator"] = { fg = p.fg },
    ["@operator.go"] = { fg = p.cyan },
    ["@property"] = { fg = p.purple2 },
    ["@punctuation"] = { fg = p.fg },
    ["@punctuation.bracket"] = { fg = p.pink },
    ["@punctuation.bracket.c"] = { fg = p.fg },
    ["@punctuation.bracket.cpp"] = { fg = p.fg },
    ["@punctuation.bracket.java"] = { fg = p.fg },
    ["@punctuation.bracket.php"] = { fg = p.fg },
    ["@punctuation.bracket.python"] = { fg = p.fg },
    ["@punctuation.delimiter"] = { fg = p.fg },
    ["@punctuation.special"] = { fg = p.cyan },
    ["@string"] = { fg = p.pink },
    ["@string.documentation"] = { fg = p.pink },
    ["@string.escape"] = { fg = p.fg },
    ["@string.regexp"] = { fg = p.fg },
    ["@string.special"] = { fg = p.green2 },
    ["@tag"] = { fg = p.steel },
    ["@tag.attribute"] = { fg = p.purple },
    ["@tag.delimiter"] = { fg = p.punctuation_tag },
    ["@type"] = { fg = p.peach },
    ["@type.builtin"] = { fg = p.cyan2 },
    ["@type.definition"] = { fg = p.peach },
    ["@type.definition.go"] = { fg = p.peach },
    ["@variable"] = { fg = p.fg },
    ["@variable.builtin"] = { fg = p.self },
    ["@variable.member"] = { fg = p.purple2 },
    ["@variable.parameter"] = { fg = p.fg },
    ["@variable.parameter.builtin"] = { fg = p.peach },

    ["@constant.builtin.python"] = { fg = p.cyan2 },
    ["@constructor.python"] = { fg = p.steel },
    ["@function.call.python"] = { fg = p.purple },
    ["@function.method.call.php"] = { fg = p.purple },
    ["@function.call.php"] = { fg = p.purple },
    ["@keyword.import.python"] = { fg = p.cyan, italic = M.config.italic_keywords },
    ["@keyword.return.python"] = { fg = p.cyan, italic = M.config.italic_keywords },
    ["@keyword.operator.php"] = { fg = p.cyan },
    ["@keyword.operator.go"] = { fg = p.cyan },
    ["@keyword.operator.rust"] = { fg = p.cyan },
    ["@punctuation.special.go"] = { fg = p.cyan },
    ["@module.go"] = { fg = p.peach },
    ["@punctuation.special.markdown"] = { fg = p.fg },
    ["@string.special.url.markdown"] = { fg = p.purple, underline = true },
    ["@tag.builtin"] = { fg = p.purple3 },
    ["@type.any.go"] = { fg = p.peach },
    ["@type.builtin.typescript"] = { fg = p.cyan2 },
    ["@type.builtin.tsx"] = { fg = p.cyan2 },
    ["@variable.builtin.rust"] = { fg = p.fg },
    ["@variable.parameter.python"] = { fg = p.yellow2 },

    ["@lsp.type.class"] = { fg = p.steel },
    ["@lsp.type.decorator"] = { fg = p.green2 },
    ["@lsp.type.enum"] = { fg = p.peach },
    ["@lsp.type.enumMember"] = { fg = p.fg },
    ["@lsp.type.function"] = function_semantic_style,
    ["@lsp.type.interface"] = { fg = p.peach },
    ["@lsp.type.macro"] = { fg = p.green2 },
    ["@lsp.type.method"] = function_semantic_style,
    ["@lsp.type.namespace"] = { fg = p.fg_sidebar },
    ["@lsp.type.parameter"] = { fg = p.fg },
    ["@lsp.type.property"] = { fg = p.purple2 },
    ["@lsp.type.struct"] = { fg = p.peach },
    ["@lsp.type.struct.go"] = { fg = p.peach },
    ["@lsp.type.type"] = { fg = p.peach },
    ["@lsp.type.type.go"] = { fg = p.peach },
    ["@lsp.type.typeParameter"] = { fg = p.cyan },
    ["@lsp.type.variable"] = { fg = p.fg },
    ["@lsp.typemod.function.declaration"] = function_declaration_style,
    ["@lsp.typemod.method.declaration"] = function_declaration_style,
    ["@lsp.typemod.property.declaration"] = { fg = p.purple2, bold = true },
    ["@lsp.typemod.struct.declaration"] = { fg = p.peach },
    ["@lsp.typemod.struct.declaration.go"] = { fg = p.peach },
    ["@lsp.typemod.type.declaration"] = { fg = p.peach },
    ["@lsp.typemod.type.declaration.go"] = { fg = p.peach },
    ["@lsp.typemod.class.defaultLibrary"] = { fg = p.cyan2 },
    ["@lsp.typemod.type.defaultLibrary"] = { fg = p.cyan2 },
    ["@lsp.typemod.variable.defaultLibrary"] = { fg = p.fg },
    ["@lsp.typemod.variable.globalScope"] = { fg = p.green2 },
    ["@lsp.typemod.variable.readonly"] = { fg = p.fg_sidebar },
    ["@lsp.typemod.variable.constant"] = { fg = p.cyan },
    ["@lsp.typemod.function.defaultLibrary"] = { fg = p.cyan2 },
    ["@lsp.typemod.method.defaultLibrary"] = { fg = p.cyan2 },

    TelescopeNormal = { fg = p.fg, bg = bg_float },
    TelescopeBorder = { fg = p.border, bg = bg_float },
    TelescopePromptNormal = { fg = p.fg, bg = p.bg_input },
    TelescopePromptBorder = { fg = p.border, bg = p.bg_input },
    TelescopePromptPrefix = { fg = p.blue, bg = p.bg_input },
    TelescopePromptTitle = { fg = p.fg, bg = p.blue },
    TelescopePreviewTitle = { fg = p.fg, bg = p.green },
    TelescopeResultsTitle = { fg = p.fg, bg = p.purple_focus },
    TelescopeSelection = { fg = p.fg, bg = p.bg_visual },
    TelescopeMatching = { fg = p.fg, bold = true },

    CmpItemAbbr = { fg = p.fg },
    CmpItemAbbrDeprecated = { fg = p.fg_muted, strikethrough = true },
    CmpItemAbbrMatch = { fg = p.fg, bold = true },
    CmpItemAbbrMatchFuzzy = { fg = p.fg, bold = true },
    CmpItemKind = { fg = p.purple },
    CmpItemKindClass = { fg = p.steel },
    CmpItemKindColor = { fg = p.gold },
    CmpItemKindConstant = { fg = p.yellow2 },
    CmpItemKindConstructor = { fg = p.steel },
    CmpItemKindEnum = { fg = p.peach },
    CmpItemKindEnumMember = { fg = p.fg },
    CmpItemKindField = { fg = p.purple2 },
    CmpItemKindFile = { fg = p.fg },
    CmpItemKindFolder = { fg = p.fg_sidebar },
    CmpItemKindFunction = { fg = p.peach },
    CmpItemKindInterface = { fg = p.peach },
    CmpItemKindKeyword = { fg = p.cyan },
    CmpItemKindMethod = { fg = p.gold },
    CmpItemKindModule = { fg = p.peach },
    CmpItemKindOperator = { fg = p.fg },
    CmpItemKindProperty = { fg = p.purple2 },
    CmpItemKindReference = { fg = p.fg },
    CmpItemKindSnippet = { fg = p.green2 },
    CmpItemKindStruct = { fg = p.steel },
    CmpItemKindText = { fg = p.fg },
    CmpItemKindTypeParameter = { fg = p.cyan },
    CmpItemKindUnit = { fg = p.gold },
    CmpItemKindValue = { fg = p.pink },
    CmpItemKindVariable = { fg = p.fg },
    CmpItemMenu = { fg = p.fg_muted },

    GitSignsAdd = { fg = p.git_add, bg = bg },
    GitSignsChange = { fg = p.git_change, bg = bg },
    GitSignsDelete = { fg = p.git_delete, bg = bg },
    GitSignsCurrentLineBlame = { fg = p.fg_muted },
    GitSignsAddInline = { bg = p.bg_diff_add },
    GitSignsChangeInline = { bg = p.bg_merge_incoming },
    GitSignsDeleteInline = { bg = p.bg_diff_delete },
    MiniDiffSignAdd = { fg = p.git_add, bg = bg },
    MiniDiffSignChange = { fg = p.git_change, bg = bg },
    MiniDiffSignDelete = { fg = p.git_delete, bg = bg },

    NvimTreeNormal = { fg = p.fg_sidebar, bg = p.bg_sidebar },
    NvimTreeNormalNC = { fg = p.fg_sidebar, bg = p.bg_sidebar },
    NvimTreeEndOfBuffer = { fg = p.bg_sidebar, bg = p.bg_sidebar },
    NvimTreeFolderName = { fg = p.fg_sidebar },
    NvimTreeOpenedFolderName = { fg = p.fg },
    NvimTreeRootFolder = { fg = p.fg, bold = true },
    NvimTreeGitDirty = { fg = p.git_change },
    NvimTreeGitNew = { fg = p.git_add },
    NvimTreeGitDeleted = { fg = p.git_delete },
    NeoTreeNormal = { fg = p.fg_sidebar, bg = p.bg_sidebar },
    NeoTreeNormalNC = { fg = p.fg_sidebar, bg = p.bg_sidebar },
    NeoTreeDirectoryName = { fg = p.fg_sidebar },
    NeoTreeDirectoryIcon = { fg = p.steel },
    NeoTreeGitModified = { fg = p.git_change },
    NeoTreeGitAdded = { fg = p.git_add },
    NeoTreeGitDeleted = { fg = p.git_delete },

    WhichKey = { fg = p.purple },
    WhichKeyDesc = { fg = p.fg },
    WhichKeyGroup = { fg = p.steel },
    WhichKeySeparator = { fg = p.fg_muted },
    WhichKeyFloat = { bg = bg_float },

    LazyNormal = { fg = p.fg, bg = bg_float },
    MasonNormal = { fg = p.fg, bg = bg_float },
    DapUIBreakpointsCurrentLine = { fg = p.fg, bg = p.bg_marker_navigation },
    DapUIBreakpointsInfo = { fg = p.green },
    DapUIBreakpointsLine = { fg = p.fg_line_nr },
    DapUIBreakpointsPath = { fg = p.steel },
    DapUIDecoration = { fg = p.border },
    DapUIFloatBorder = { fg = p.border, bg = bg_float },
    DapUILineNumber = { fg = p.fg_line_nr },
    DapUIModifiedValue = { fg = p.git_change },
    DapUIPlayPause = { fg = p.green },
    DapUIRestart = { fg = p.green },
    DapUIScope = { fg = p.steel },
    DapUIStop = { fg = p.red },
    DapUIStoppedThread = { fg = p.fg, bg = p.bg_debug_toolbar },
    DapUIThread = { fg = p.fg },
    DapUIType = { fg = p.cyan2 },
    DapUIUnavailable = { fg = p.fg_muted },
    DapUIWatchesEmpty = { fg = p.red },
    DapUIWatchesError = { fg = p.red },
    DapUIWatchesValue = { fg = p.fg },
    NoiceCmdlinePopup = { fg = p.fg, bg = bg_float },
    NoiceCmdlinePopupBorder = { fg = p.border, bg = bg_float },
    NotifyBackground = { bg = bg_float },
  }

  apply(highlights)

  if M.config.terminal_colors then
    set_terminal_colors(p)
  end
end

return M
